export const restaurantsConstants = {
  GET_RESTAURANTS_REQUEST: 'GET_RESTAURANTS_REQUEST',
  GET_RESTAURANTS_SUCCESS: 'GET_RESTAURANTS_SUCCESS',
  SET_RESTAURANT_APPLICATIONS_REQUEST: 'SET_RESTAURANT_APPLICATIONS_REQUEST',
  SET_RESTAURANT_APPLICATIONS_SUCCESS: 'SET_RESTAURANT_APPLICATIONS_SUCCESS',
  UNSET_RESTAURANT_APPLICATIONS_SUCCESS: 'UNSET_RESTAURANT_APPLICATIONS_SUCCESS'
};
